name: venv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

# SEZIONE 1: Tutte le dipendenze vanno qui (una sola volta)
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  
  # Le librerie per la mappa (aggiunte qui)
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# SEZIONE 2: Configurazione Flutter e Assets (una sola volta)
flutter:
  uses-material-design: true

  # Qui registriamo il file JSON
  assets:
    - assets/venezia.geojson